Feat/stop danmaku
luyuhuang/DWords2 pull request #6
Opened 2021-11-01 07:42 UTC by MrPand111

说下我的思路：通过全局的stop控制是否暂停弹幕，然后和初始化调用同一个函数（这里我不太清楚是否可以抽离开启弹幕和监听的方法，如果可以的话`Run/Stop Danmaku`这里调用一个更小的controllDanmaku函数），通过isStop来清除已有的定时器并阻止新的弹幕被创建

2021-11-01 08:15 UTC, MrPand111 commented on src/dwords.js
> +                initDanmaku(dwords, dwords.stop);
你说的对 其实都不需要传参数了，dwords这个大对象中已经包含了信息，而且通过setDanmakuLauncher就可以控制，我重新push了，可以看下

2021-11-01 14:17 UTC, luyuhuang requested changes

2021-11-01 14:17 UTC, luyuhuang commented on src/danmaku.js
> +    if (dwords.danmakuLauncher || dwords.isDanmakuPaused) {
不用这样呀, 在下面的 `launchDanmaku` 加个 `if (dwords.isDanmakuPaused) return;` 不就好啦.

2021-11-01 14:25 UTC, MrPand111 commented on src/danmaku.js
> +    if (dwords.danmakuLauncher || dwords.isDanmakuPaused) {
嗯嗯 我再下面的函数里面加了

2021-11-02 06:35 UTC, luyuhuang requested changes

2021-11-02 06:35 UTC, luyuhuang commented on src/dwords.js
> +                setDanmakuLauncher(dwords);
这里也不用调用了

2021-11-02 06:35 UTC, luyuhuang commented on src/danmaku.js
> +    setDanmakuLauncher
这里也可以去掉

2021-11-02 06:40 UTC, MrPand111 commented on src/dwords.js
> +                setDanmakuLauncher(dwords);
是的哈，danmakuLauncher就是发射弹幕的最小粒度控制方法，其实只关注这个就行，现在这块代码差不多多明白了哈哈

2021-11-02 06:40 UTC, MrPand111 commented on src/danmaku.js
> +    setDanmakuLauncher
done

2021-11-02 06:42 UTC, luyuhuang approved these changes
好的, 多谢~

2021-11-02 06:42 UTC, merged